# Generated by Django 5.1.3 on 2024-12-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=500)),
            ],
        ),
    ]
